"""Mock 백엔드 — 키/GPU 없이 파이프라인 전체를 검증하기 위한 결정론적 더미.

이미지 경로/크기 해시로 그럴듯한 값을 안정적으로 생성한다(같은 입력 → 같은 출력).
실제 추론은 하지 않으며, API 키가 생기면 anthropic/openai 백엔드로 교체한다.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Optional

from ..keywords import keyword_parse_query
from ..schemas import ConceptPrompt, DamageInstance, ImageAnalysis
from .base import VLMBackend, image_size

_SCENE = ["highway", "urban_road", "alley", "rural_road"]
_SURFACE = ["asphalt", "asphalt", "concrete", "unpaved"]
_WEATHER = ["clear", "cloudy", "rain", "clear"]
_TIME = ["day", "day", "night", "dawn_dusk"]
_DAMAGE_POOL = ["pothole", "crack", "alligator_crack", "rutting", "patch"]
_SEVERITY = ["low", "medium", "high"]


def _seed(path: str) -> int:
    w, h = image_size(path)
    key = f"{Path(path).name}:{w}x{h}"
    return int(hashlib.sha256(key.encode("utf-8")).hexdigest(), 16)


class MockVLM(VLMBackend):
    name = "mock"
    model = "mock-deterministic-v1"

    def analyze_image(
        self, image_path: str, *, instruction: Optional[str] = None
    ) -> ImageAnalysis:
        s = _seed(image_path)
        name = Path(image_path).name.lower()

        scene = _SCENE[s % len(_SCENE)]
        surface = _SURFACE[(s // 7) % len(_SURFACE)]
        weather = _WEATHER[(s // 13) % len(_WEATHER)]
        tod = _TIME[(s // 17) % len(_TIME)]

        # 파일명 힌트가 있으면 그 손상을 강제, 없으면 해시로 결정
        hinted = [c for k, c in {
            "pothole": "pothole",
            "crack": "crack",
            "rut": "rutting",
            "patch": "patch",
        }.items() if k in name]

        damages: list[DamageInstance] = []
        if any(k in name for k in ("clean", "good", "intact")):
            pass  # 파일명 힌트: 손상 없음
        elif hinted:
            for c in hinted:
                damages.append(
                    DamageInstance(
                        type=c,
                        severity=_SEVERITY[(s // 3) % 3],
                        confidence=round(0.6 + (s % 35) / 100.0, 2),
                        description=f"{c} detected (mock).",
                    )
                )
        elif s % 3 != 0:  # 약 2/3 확률로 손상 있음
            n = 1 + (s % 2)
            for i in range(n):
                c = _DAMAGE_POOL[(s // (i + 2)) % len(_DAMAGE_POOL)]
                damages.append(
                    DamageInstance(
                        type=c,
                        severity=_SEVERITY[(s // (i + 5)) % 3],
                        confidence=round(0.5 + ((s // (i + 1)) % 45) / 100.0, 2),
                        description=f"{c} estimated (mock).",
                    )
                )

        damage_present = len(damages) > 0
        if not damage_present:
            condition = "good"
        elif any(d.severity == "high" for d in damages):
            condition = "poor"
        else:
            condition = "fair"

        cap = (
            f"A {weather} {tod} view of an {surface} {scene.replace('_', ' ')}"
            + (f" showing {', '.join(d.type for d in damages)}." if damages else " in good condition.")
        )
        return ImageAnalysis(
            caption=cap,
            scene_type=scene,
            surface_material=surface,
            weather=weather,
            time_of_day=tod,
            damage_present=damage_present,
            damages=damages,
            overall_condition=condition,
            notes="Generated by MockVLM (no real inference).",
        )

    def vqa(self, image_path: str, question: str) -> str:
        a = self.analyze_image(image_path)
        return (
            f"[mock] Based on the image ({a.caption}) - "
            f"damage_present={a.damage_present}, "
            f"types={sorted({d.type for d in a.damages}) or 'none'}. "
            f"(Question was: {question})"
        )

    def parse_query(self, query: str) -> ConceptPrompt:
        return keyword_parse_query(query)
